<odoo>

     <record model="ir.module.category" id="module_ol_exception">
        <field name="name">OnLogic Exception</field>
        <field name="description">Category for OnLogic Exception</field>
    </record>

    <record id="base_exception.group_exception_rule_manager" model="res.groups">
        <field name="users" eval="[(4, ref('base.user_root')), (4, ref('base.user_admin'))]" />
        <field name="category_id" ref="module_ol_exception" />
    </record>

    <record id="group_exception_python" model="res.groups">
        <field name="name">Exception: Python</field>
        <field name="users" eval="[(4, ref('base.user_root')), (4, ref('base.user_admin'))]" />
        <field name="category_id" ref="module_ol_exception" />
    </record>

</odoo>
